version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng-net
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: searxng
    ports:
      - "8888:8888"
    volumes:
      - ./searx/settings.yml:/etc/searxng/settings.yml:ro
      - searxng-logs:/var/log/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888/
      - SEARXNG_BIND_ADDRESS=0.0.0.0
      - SEARXNG_PORT=8888
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/usr/local/searxng
      - ES_URL=http://es:9200
    depends_on:
      - redis
      - es
      - simple-crawler
    restart: unless-stopped
    networks:
      - searxng-net
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - searxng-net
    volumes:
      - esdata:/usr/share/elasticsearch/data

  simple-crawler:
    build:
      context: .
      dockerfile: simple-crawler.dockerfile
    container_name: simple-crawler
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - searxng-net
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  redis-data:
  searxng-logs:
  esdata:

networks:
  searxng-net:
    driver: bridge

  # Elasticsearch 单节点，用于 BM25 + 时间衰减重排
